name: UAT Deploy (Azure Static Web Apps)

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, closed]
    paths-ignore:
      - "**.md"
      - "**.ps1"
      - ".editorconfig"
      - "TestFiles/*"
      - "**/*.gitignore"
      - "**/*.gitattributes"
      - "**/*.yml"

jobs:
  build_and_deploy:
    name: Build and Deploy UAT
    runs-on: ubuntu-latest
    if: github.event.action != 'closed'
    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.2

      - name: Setup .NET
        uses: actions/setup-dotnet@v5.2.0
        with:
          global-json-file: ./global.json

      - name: Install WASM workload
        run: dotnet workload install wasm-tools

      - name: Restore dependencies
        run: dotnet restore Pkmds.Web/Pkmds.Web.csproj

      - name: Publish
        run: dotnet publish Pkmds.Web/Pkmds.Web.csproj -c Release -o release --nologo

      - name: Copy index.html to 404.html
        run: cp release/wwwroot/index.html release/wwwroot/404.html

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: release/wwwroot
          skip_app_build: true

  close_staging:
    name: Close UAT Staging Environment
    runs-on: ubuntu-latest
    if: github.event.action == 'closed'
    steps:
      - name: Close staging environment
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: close
